namespace GrblHalSender.GrblCore;

public enum grblHALSetting
{
    PulseMicroseconds = 0,
    StepperIdleLockTime = 1,
    StepInvertMask = 2,
    DirInvertMask = 3,
    InvertStepperEnable = 4,
    LimitPinsInvertMask = 5,
    InvertProbePin = 6,
    StatusReportMask = 10,
    JunctionDeviation = 11,
    ArcTolerance = 12,
    ReportInches = 13,
    ControlInvertMask = 14, // Note: Used for detecting GrblHAL firmware
    CoolantInvertMask = 15,
    SpindleInvertMask = 16,
    ControlPullUpDisableMask = 17,
    LimitPullUpDisableMask = 18,
    ProbePullUpDisable = 19,
    SoftLimitsEnable = 20,
    HardLimitsEnable = 21,
    HomingEnable = 22,
    HomingDirMask = 23,
    HomingFeedRate = 24,
    HomingSeekRate = 25,
    HomingDebounceDelay = 26,
    HomingPulloff = 27,
    G73Retract = 28,
    PulseDelayMicroseconds = 29,
    RpmMax = 30,
    RpmMin = 31,
    Mode = 32, // enum GrblMode
    PWMFreq = 33,
    PWMOffValue = 34,
    PWMMinValue = 35,
    PWMMaxValue = 36,
    StepperDeenergizeMask = 37,
    SpindlePPR = 38,
    EnableLegacyRTCommands = 39,
    SoftLimitJogging = 40,
    HomingLocateCycles = 43,
    HomingCycle_1 = 44,
    HomingCycle_2 = 45,
    HomingCycle_3 = 46,
    HomingCycle_4 = 47,
    HomingCycle_5 = 48,
    HomingCycle_6 = 49,
    JogStepSpeed = 50,
    JogSlowSpeed = 51,
    JogFastSpeed = 52,
    JogStepDistance = 53,
    JogSlowDistance = 54,
    JogFastDistance = 55,
    // Per axis settings
    TravelResolutionBase = 100,
    MaxFeedRateBase = 110,
    AccelerationBase = 120,
    MaxTravelBase = 130,
    MaxTravelYBase = 131,
    MaxTravelZBase = 132,
    MotorCurrentBase = 140,
    MicroStepsBase = 150,
    StallGuardBase = 200,
    // End per axis settings
    ToolChangeMode = 341,
    AutoReport = 481
}